FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libffi-dev \
    && pip install --no-cache-dir rns==1.1.3 \
    && apt-get purge -y --auto-remove gcc \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/reticulum /var/lib/reticulum

CMD ["rnsd", "--config", "/etc/reticulum", "-vvv"]
